# Site settings
title: Yijun Wu's github page
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Yijun Wu, a technical guy who is also interested in making the world a better place.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yijunwu.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username:  yijunwu

# Build settings
markdown: kramdown
